blank_issues_enabled: false

contact_links:
  - name: Cora Programming Language
    url: https://github.com/djoezeke/cora
    about: Modern Scripting Language.

  - name: Cora Discussions ğŸ’–
    url: https://github.com/djoezeke/cora/discussions
    about: The "Discussions" forum is where you want to start.

  - name: Cora Issues | Bug Bounty ğŸ
    url: https://github.com/djoezeke/cora/issues
    about: Please report issues and vulnerabilities here.

  - name: Cora Releases
    url: https://github.com/djoezeke/cora/releases
    about: Please latest Cora release here.
